title: Cours 01
tagline: A brand new course on Learning Lab
description: Lorem ipsum
template:
  repo: cours-01-template
  name: cours-01
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
